"""Add detailed fields to voice_models table

Revision ID: 25332d4efd14
Revises: 
Create Date: 2025-10-13 15:33:31.157637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25332d4efd14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_models', sa.Column('name', sa.String(), nullable=False, comment="模型的显示名称，例如 '蔡徐坤'"))
    op.add_column('voice_models', sa.Column('handle', sa.String(), nullable=False, comment="模型的唯一句柄/ID，例如 'xiaotang911991'"))
    op.add_column('voice_models', sa.Column('description', sa.TEXT(), nullable=True, comment='模型的描述或试听语音的文本'))
    op.add_column('voice_models', sa.Column('avatar_url', sa.String(), nullable=True, comment='头像图片的URL'))
    op.add_column('voice_models', sa.Column('preview_audio_url', sa.String(), nullable=True, comment='试听语音文件的URL'))
    op.add_column('voice_models', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='标签数组，用于搜索和分类'))
    op.add_column('voice_models', sa.Column('play_count', sa.Integer(), nullable=False, comment='播放/试听次数'))
    op.add_column('voice_models', sa.Column('share_count', sa.Integer(), nullable=False, comment='分享次数'))
    op.add_column('voice_models', sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞/喜欢次数'))
    op.add_column('voice_models', sa.Column('save_count', sa.Integer(), nullable=False, comment='收藏次数'))
    op.add_column('voice_models', sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'))
    op.add_column('voice_models', sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开可见'))
    op.add_column('voice_models', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后更新时间'))
    op.alter_column('voice_models', 'provider',
               existing_type=sa.VARCHAR(),
               comment='声音来源或提供方',
               existing_nullable=True)
    op.alter_column('voice_models', 'language',
               existing_type=sa.VARCHAR(),
               comment='主要语言',
               existing_nullable=True)
    op.alter_column('voice_models', 'gender',
               existing_type=sa.VARCHAR(),
               comment='性别',
               existing_nullable=True)
    op.alter_column('voice_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_voice_models_model_name'), table_name='voice_models')
    op.create_index('ix_voice_models_tags', 'voice_models', ['tags'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uq_voice_models_handle', 'voice_models', ['handle'])
    op.create_unique_constraint('uq_voice_models_name', 'voice_models', ['name'])
    op.drop_column('voice_models', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_models', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_voice_models_name', 'voice_models', type_='unique')
    op.drop_constraint('uq_voice_models_handle', 'voice_models', type_='unique')
    op.drop_index('ix_voice_models_tags', table_name='voice_models', postgresql_using='gin')
    op.create_index(op.f('ix_voice_models_model_name'), 'voice_models', ['model_name'], unique=True)
    op.alter_column('voice_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_models', 'gender',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='性别',
               existing_nullable=True)
    op.alter_column('voice_models', 'language',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='主要语言',
               existing_nullable=True)
    op.alter_column('voice_models', 'provider',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='声音来源或提供方',
               existing_nullable=True)
    op.drop_column('voice_models', 'updated_at')
    op.drop_column('voice_models', 'is_public')
    op.drop_column('voice_models', 'usage_count')
    op.drop_column('voice_models', 'save_count')
    op.drop_column('voice_models', 'like_count')
    op.drop_column('voice_models', 'share_count')
    op.drop_column('voice_models', 'play_count')
    op.drop_column('voice_models', 'tags')
    op.drop_column('voice_models', 'preview_audio_url')
    op.drop_column('voice_models', 'avatar_url')
    op.drop_column('voice_models', 'description')
    op.drop_column('voice_models', 'handle')
    op.drop_column('voice_models', 'name')
    # ### end Alembic commands ###
